[versions]
log4j = "2.25.2"
netty = "4.2.7.Final"

[libraries]
netty-codec-base = { module = "io.netty:netty-codec-base", version.ref = "netty" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }

[bundles]


[plugins]
